pull_request_rules:

  - name: Automatic merge (renovate)
    description: Merge renovate PRs when they are up to date, pass all branch protections and has mergeable label
    conditions:
      - 'label = mergeable'
      - 'author = renovate[bot]'
      - '#commits-behind = 0'
    actions:
      merge:

  - name: Automatic merge (main)
    description: Merge PRs when they pass all branch protections and has mergeable label
    conditions:
      - 'label = mergeable'
      - 'author != renovate[bot]'
    actions:
      queue:
        
