pull_request_rules:

  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - label = mergeable
      - base = master
    actions:
      queue:

  - name: Make sure PR are up to date before merging
    description: This automatically updates PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions:
      - author != renovate[bot]  # Don't rebase renovate PRs
    actions:
      rebase:
